name = input("请输入你的名字：")
company = input("请输入你的公司名：")
title  = input("请输入你的职位：")
phone = input("请输入你的手机号：")
email = input("请输入你的邮箱：")
print("************************")
print("姓名：", name)
print("公司：", company)
print("职位：", title)
print("手机号：", phone)
print("邮箱：", email)
print("************************")